name: Setup Node
description: "Setup Node.js environment"
inputs:
  node-version:
    description: "Node version to use."
    required: true

runs:
  using: "composite"
  steps:
    - uses: nrwl/nx-set-shas@v4
    - uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ inputs.node-version }}-
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: https://registry.npmjs.org
    - run: npm install --global npm@11.1.0
      shell: bash
