name: Setup Node
description: "Setup Node.js environment"

inputs:
  npm_token:
    description: The `NPM_TOKEN` to download private NPM packages.
    required: true

runs:
  using: "composite"
  steps:
    - uses: nrwl/nx-set-shas@v4
    - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('.nvmrc') }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ hashFiles('.nvmrc') }}-
    - uses: ClipboardHealth/action-build-nodejs@v3
      with:
        npm_token: ${{ inputs.npm_token }}
