name: Setup Node
description: "Setup Node.js environment"

runs:
  using: "composite"
  steps:
    - uses: nrwl/nx-set-shas@v4
    - uses: actions/cache@v5
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('.nvmrc') }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ hashFiles('.nvmrc') }}-
    - uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        registry-url: https://registry.npmjs.org
