export * from "./lib/deepFreeze";
export * as either from "./lib/either";
export * from "./lib/isDefined";
export * from "./lib/isError";
export * from "./lib/isNil";
export * from "./lib/isString";
export * as option from "./lib/option";
export * from "./lib/pipe";
export * from "./lib/stringify";
export * from "./lib/toError";
export * from "./lib/types";
