services:
  test-mongo:
    image: mongo:8.2@sha256:d343c378b5c6e2fe373174abcf4a877be0dfc721b5d0b9d582204dccb1c00b86
    command: --replSet "rs0"
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - cbh-mongo:/data/db
    healthcheck:
      test: mongosh --quiet --eval "db.isWritablePrimary()" || mongosh --quiet --eval "rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}).ok"
      interval: 10s
      start_period: 30s
      timeout: 5s
      retries: 3

volumes:
  cbh-mongo:
