export const DEFAULT_REMOTE_SETUP_COMMAND = [
  [
    "if [ -f .nvmrc ]; then",
    "required_node=$(tr -d '[:space:]' < .nvmrc | sed 's/^v//')",
    'current_node=$(node --version 2>/dev/null | sed "s/^v//")',
    'if [ -n "$required_node" ] && [ "$current_node" != "$required_node" ]; then',
    `if [ -n "\${NVM_DIR:-}" ] && [ -s "$NVM_DIR/nvm.sh" ]; then`,
    '. "$NVM_DIR/nvm.sh"',
    'nvm install "$required_node"',
    'nvm alias default "$required_node"',
    'nvm use "$required_node"',
    'elif [ -s "/.sprite/languages/node/nvm/nvm.sh" ]; then',
    'export NVM_DIR="/.sprite/languages/node/nvm"',
    '. "$NVM_DIR/nvm.sh"',
    'nvm install "$required_node"',
    'nvm alias default "$required_node"',
    'nvm use "$required_node"',
    "else",
    "npm install --global n --no-audit --no-fund",
    'n_path="$(command -v n || true)"',
    'if [ -z "$n_path" ]; then n_path="$(npm prefix -g)/bin/n"; fi',
    'if "$n_path" "$required_node"; then :; elif command -v sudo >/dev/null 2>&1; then sudo "$n_path" "$required_node"; else exit 1; fi',
    "fi",
    "hash -r",
    "fi",
    "fi",
  ].join("\n"),
  "required_npm=$(node -e \"try { console.log(require('./package.json').engines?.npm ?? '') } catch { console.log('') }\")",
  'if [ -n "$required_npm" ]; then npm install --global "npm@$required_npm" --no-audit --no-fund && hash -r; fi',
  "if [ -x .claude/setup.sh ]; then ./.claude/setup.sh --deps-only; elif [ -f .claude/setup.sh ] && command -v bash >/dev/null 2>&1; then bash .claude/setup.sh --deps-only; else npm clean-install; fi",
].join(" && ");
