import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { PATHS } from "./constants";
import { discoverRules, generateReadmeRulesSection } from "./rules";

const START_MARKER = "<!-- START: Auto-generated by ./scripts/populateReadme.ts -->";
const END_MARKER = "<!-- END: Auto-generated by ./scripts/populateReadme.ts -->";

async function populateReadme(): Promise<void> {
  const readmePath = path.join(PATHS.packageRoot, "README.md");
  const readme = await readFile(readmePath, "utf8");

  const startIndex = readme.indexOf(START_MARKER);
  const endIndex = readme.indexOf(END_MARKER);
  if (startIndex === -1 || endIndex === -1) {
    throw new Error(`README.md is missing the '${START_MARKER}' and '${END_MARKER}' markers`);
  }

  const rules = await discoverRules(path.join(PATHS.packageRoot, "rules"));
  const updated = [
    readme.slice(0, startIndex + START_MARKER.length),
    "",
    generateReadmeRulesSection(rules),
    "",
    readme.slice(endIndex),
  ].join("\n");

  await writeFile(readmePath, updated, "utf8");
  console.log(`✅ Updated Available Rules section in ${readmePath}`);
}

// eslint-disable-next-line unicorn/prefer-top-level-await
void populateReadme();
