import { readdir, readFile } from "node:fs/promises";
import path from "node:path";

export interface RuleMetadata {
  category: string;
  description: string;
  heading: string;
  id: string;
  relativePath: string;
}

const FRONTMATTER_PATTERN = /^---\r?\n(?<frontmatter>[\s\S]*?)\r?\n---/;
const DESCRIPTION_PATTERN = /^description:\s*(?<description>.+)$/m;
const HEADING_PATTERN = /^#\s+(?<heading>.+)$/m;

/**
 * Parses a rule file's frontmatter `description` (the "When to Read" text) and its H1 heading.
 * The frontmatter is the single source of truth for rule metadata; throws when it's missing so
 * tests catch unregistered descriptions before publishing.
 */
export function parseRuleFile(params: { content: string; filePath: string }): {
  description: string;
  heading: string;
} {
  const { content, filePath } = params;

  const frontmatter = FRONTMATTER_PATTERN.exec(content)?.groups?.["frontmatter"];
  const rawDescription = frontmatter
    ? DESCRIPTION_PATTERN.exec(frontmatter)?.groups?.["description"]
    : undefined;
  if (!rawDescription) {
    throw new Error(`Rule file ${filePath} is missing a frontmatter 'description'`);
  }

  const description = stripQuotes(rawDescription.trim());
  const heading =
    HEADING_PATTERN.exec(content)?.groups?.["heading"] ?? path.basename(filePath, ".md");

  return { description, heading };
}

function stripQuotes(value: string): string {
  if (value.length >= 2 && value.startsWith('"') && value.endsWith('"')) {
    return value.slice(1, -1);
  }

  return value;
}

/**
 * Discovers rules from the rules directory: each `<category>/<name>.md` file is a rule with id
 * `<category>/<name>`. Categories are the directory names; no separate registration required.
 */
export async function discoverRules(rulesRoot: string): Promise<RuleMetadata[]> {
  const entries = await readdir(rulesRoot, { withFileTypes: true });
  const categories = entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .toSorted();

  const rules = await Promise.all(
    categories.map(async (category) => {
      const fileNames = await readdir(path.join(rulesRoot, category));
      const files = fileNames.filter((file) => file.endsWith(".md")).toSorted();

      return await Promise.all(
        files.map(async (file): Promise<RuleMetadata> => {
          const relativePath = path.join(category, file);
          const content = await readFile(path.join(rulesRoot, relativePath), "utf8");
          const { description, heading } = parseRuleFile({ content, filePath: relativePath });

          return {
            category,
            description,
            heading,
            id: `${category}/${path.basename(file, ".md")}`,
            relativePath,
          };
        }),
      );
    }),
  );

  return rules.flat();
}

/**
 * Resolves the rules to sync: profile categories expanded in order, plus includes, minus
 * excludes. Unknown ids are reported (not fatal) so a stale `--include`/`--exclude` in a consuming
 * repo degrades gracefully instead of breaking installs.
 */
export function resolveRules(params: {
  excludes: string[];
  includes: string[];
  profileCategories: readonly string[];
  rules: RuleMetadata[];
}): { rules: RuleMetadata[]; unknownIds: string[] } {
  const { excludes, includes, profileCategories, rules } = params;

  const rulesById = new Map(rules.map((rule) => [rule.id, rule]));
  const unknownIds = [...includes, ...excludes].filter((id) => !rulesById.has(id));

  const ruleIds = new Set([
    ...profileCategories.flatMap((category) =>
      rules.filter((rule) => rule.category === category).map((rule) => rule.id),
    ),
    ...includes.filter((id) => rulesById.has(id)),
  ]);
  for (const id of excludes) {
    ruleIds.delete(id);
  }

  return {
    rules: [...ruleIds].map((id) => rulesById.get(id)).filter((rule) => rule !== undefined),
    unknownIds,
  };
}

export function generateAgentsIndex(rules: RuleMetadata[]): string {
  const rows = rules.map(
    (rule) =>
      `| ${rule.heading} | .rules/${toPosixPath(rule.relativePath)} | ${rule.description} |`,
  );

  return [
    "<!-- Generated by @clipboard-health/ai-rules -->",
    "",
    "# Coding Rules",
    "",
    "IMPORTANT: You MUST read the relevant rule files below before writing or reviewing code.",
    "",
    "| Rule | File | When to Read |",
    "|------|------|-------------|",
    ...rows,
    "",
    "## Agent Skills",
    "",
    "Agent skills are linked from `node_modules/@clipboard-health/ai-rules` into `.agents/`.",
    "If a referenced skill is missing or unreadable, run `npm ci` from the repository root and retry.",
    "",
  ].join("\n");
}

/**
 * Generates the README "Available Rules" tables from rule frontmatter. A test asserts the README
 * contains this exact content; run scripts/populateReadme.ts after changing rules.
 */
export function generateReadmeRulesSection(rules: RuleMetadata[]): string {
  const categories = [...new Set(rules.map((rule) => rule.category))].toSorted();

  const sections = categories.map((category) => {
    const rows = rules
      .filter((rule) => rule.category === category)
      .map((rule) => `| \`${rule.id}\` | ${rule.description} |`);

    return [`### ${category}`, "", "| Rule ID | When to Read |", "| --- | --- |", ...rows].join(
      "\n",
    );
  });

  return sections.join("\n\n");
}

function toPosixPath(filePath: string): string {
  return filePath.split(path.sep).join("/");
}
